<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>GenshinPiano</AssemblyName>
    <RootNamespace>GenshinPiano.App</RootNamespace>
    <ApplicationIcon>Assets\Icons\GenshinPiano.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>3.0.1-preview.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GenshinPiano.Application\GenshinPiano.Application.csproj" />
    <ProjectReference Include="..\GenshinPiano.Infrastructure\GenshinPiano.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\Icons\GenshinPiano.ico" />
    <AssemblyMetadata Include="GenshinPianoSelfContained" Value="$(SelfContained)" />
  </ItemGroup>
</Project>
